# Generated by Django 6.0.3 on 2026-04-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="password_hash",
            field=models.TextField(blank=True, null=True),
        ),
    ]
